const environment = {
  development: {
    APP_PORT: process.env.APP_PORT,
    APP_HOST: process.env.APP_HOST,
    MONGO_USERNAME: process.env.MONGO_USERNAME,
    MONGO_PASSWORD: process.env.MONGO_PASSWORD,
    MONGO_HOSTNAME: process.env.MONGO_HOSTNAME,
    MONGO_PORT: process.env.MONGO_PORT,
    MONGO_DB: process.env.MONGO_DB,
    MONGO_AUTH: process.env.MONGO_AUTH,
    JWT_SECRET: process.env.JWT_SECRET,
    BCRYPT_ROUND: process.env.BCRYPT_ROUND,
    CLOUD_NAME: process.env.CLOUD_NAME,
    CLOUD_KEY: process.env.CLOUD_KEY,
    CLOUD_SECRET: process.env.CLOUD_SECRET,
    CONSUMER_KEY: process.env.CONSUMER_KEY,
    CONSUMER_SECRET: process.env.CONSUMER_SECRET,
    TWEET_TOKEN_KEY: process.env.TWEET_TOKEN_KEY,
    TWEET_TOKEN_SECRET: process.env.TWEET_TOKEN_SECRET,
  },
  production: {
    APP_PORT: process.env.APP_PORT,
    APP_HOST: process.env.APP_HOST,
    MONGO_USERNAME: process.env.MONGO_USERNAME,
    MONGO_PASSWORD: process.env.MONGO_PASSWORD,
    MONGO_HOSTNAME: process.env.MONGO_HOSTNAME,
    MONGO_PORT: process.env.MONGO_PORT,
    MONGO_DB: process.env.MONGO_DB,
    MONGO_AUTH: process.env.MONGO_AUTH,
    JWT_SECRET: process.env.JWT_SECRET,
    BCRYPT_ROUND: process.env.BCRYPT_ROUND,
    CLOUD_NAME: process.env.CLOUD_NAME,
    CLOUD_KEY: process.env.CLOUD_KEY,
    CLOUD_SECRET: process.env.CLOUD_SECRET,
    CONSUMER_KEY: process.env.CONSUMER_KEY,
    CONSUMER_SECRET: process.env.CONSUMER_SECRET,
    TWEET_TOKEN_KEY: process.env.TWEET_TOKEN_KEY,
    TWEET_TOKEN_SECRET: process.env.TWEET_TOKEN_SECRET,
  },
};

module.exports = environment[process.env.NODE_ENV || 'development'];
